### ISSUE TITLE
Linux Errors

### ISSUE THREAD

**Issue by diorn** [xjorma/EarthMeshHoudini#1]
Hello there, 
Thanks for the effort on what seems to be a very useful and welcomed tool
Would like to get this working if possible on linux.

Best regards!

On initial use i get this error message on the sop node:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Error | Invalid source /obj/geo1/EarthMesh1/FindAltitudeError: Python error: Traceback (most recent call last):File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1346, in do_openh.request(req.get_method(), req.selector, req.data, headers,File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1285, in requestself._send_request(method, url, body, headers, encode_chunked)File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1331, in _send_requestself.endheaders(body, encode_chunked=encode_chunked)File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1280, in endheadersself._send_output(message_body, encode_chunked=encode_chunked)File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1040, in _send_outputself.send(msg)File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 980, in sendself.connect()File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1454, in connectself.sock = self._context.wrap_socket(self.sock,File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 500, in wrap_socketreturn self.sslsocket_class._create(File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 1040, in _createself.do_handshake()File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 1309, in do_handshakeself._sslobj.do_handshake()ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)During handling of the above exception, another exception occurred:Traceback (most recent call last):File "<stdin>", line 42, in <module>File "<stdin>", line 16, in get_elevationFile "<stdin>", line 5, in bytes_from_urlFile "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 214, in urlopenreturn opener.open(url, data, timeout)File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 517, in openresponse = self._open(req, data)File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 534, in _openresult = self._call_chain(self.handle_open, protocol, protocol +File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 494, in _call_chainresult = func(*args)File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1389, in https_openreturn self.do_open(http.client.HTTPSConnection, req,File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1349, in do_openraise URLError(err)urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>.
-- | --

</body></html>Error 
Invalid source [/obj/geo1/EarthMesh1/FindAltitude](node:/obj/geo1/EarthMesh1/FindAltitude)
Error: Python error: Traceback (most recent call last):
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1346, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1285, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1331, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1280, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1040, in _send_output
self.send(msg)
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 980, in send
self.connect()
File "/opt/hfs19.5.716/python/lib/python3.9/http/client.py", line 1454, in connect
self.sock = self._context.wrap_socket(self.sock,
File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 500, in wrap_socket
return self.sslsocket_class._create(
File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 1040, in _create
self.do_handshake()
File "/opt/hfs19.5.716/python/lib/python3.9/ssl.py", line 1309, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "<stdin>", line 42, in <module>
File "<stdin>", line 16, in get_elevation
File "<stdin>", line 5, in bytes_from_url
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 214, in urlopen
return opener.open(url, data, timeout)
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 517, in open
response = self._open(req, data)
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 534, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1389, in https_open
return self.do_open(http.client.HTTPSConnection, req,
File "/opt/hfs19.5.716/python/lib/python3.9/urllib/request.py", line 1349, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
.

**Comment by xjorma** [comment]
I am nor a Linux expert nor a web request expert. But I am doing https request in python and Linux (your Linux?) don't seems to like it. I will ask some friends they might have an idea.

**Comment by gitmike24** [comment]
import ssl ssl._create_default_https_context = ssl._create_unverified_context

**Comment by gwouite** [comment]
Update the server certificate or apply the solution of @gitmike24
If the certificate is OK when navigating the URL with a classic browser (Chrome, Firefox), then you're maybe facing the bug of the root certificate of letsencrypt (late 2021) from older linux distribution that is not updated.
Solutions almost everywhere on the internet depending of the linux distribution you're using.
