### ISSUE TITLE
Working setup no longer functional. Possible API issue?

### ISSUE THREAD

**Issue by Piminski** [xjorma/EarthMeshHoudini#10]
Hi All,

First a thank you to Daniel for an amazing tool.

I recently returned to a file using Earthmesh and it is no longer working. Preiously I had it working great, even managed to figure out rendering textures in Redshift and Vray. I have the geometry cached so luckily I can still use the mesh but going forward I will not be able to create new scenes. As I have not changed anything I suspect the error must be coming from the Google API side, has anyone else experienced this?

I notice that the downloading stops early, only glb files and json, no jpeg texture files get downloaded.

Screeshot of error message on Pyhton Node
![image 4](https://github.com/xjorma/EarthMeshHoudini/assets/84422903/fd322fee-7aee-42bc-81f9-6a32fde13bcc)

Any insight advice or help is appreciated?
Is it an API issue? Or Python version issue? Or Houdini version issue?

**Comment by OGylf** [comment]
same error here ! 
it download jpeg, but all black

**Comment by ToniousT** [comment]
Encountering the same thing here

**Comment by xjorma** [comment]
I have looked into the problem and found that it's related to the filenames I'm using, which are provided by Google for caching purposes. Regrettably, Google is now supplying filenames that are excessively long. I will endeavor to develop a solution for this issue at the earliest opportunity.

**Comment by Piminski** [comment]
Aha, yes I did notice the names were very long. I thought it was something on the Google end…. Damn you Google! (Impotently shaking fist) :)

**Comment by xjorma** [comment]
Should be fixed. It's a quick fix, but should do the job.
