### ISSUE TITLE
Remove "." from pip install instructions

### ISSUE THREAD

**Issue by syntheticperson** [xjorma/EarthMeshHoudini#17]
In the documentation, you have:

Type hython -m pip install pygltflib to install the pygltflib.

Type hython -m pip install DracoPy to install DracoPy.

Please remove the "." from the end of each line.
When people copy and paste the command, it's easy to forget to delete the ".", then you get the error:

ERROR: Invalid requirement: 'DracoPy.'

Thanks

**Comment by xjorma** [comment]
I thought the "bold" was enough to understand what to copy paste. Anyway the "." is not the issue here since "to install the pygltflib" should also be removed.

**Comment by xjorma** [comment]
Fixed in:
https://github.com/xjorma/EarthMeshHoudini/commit/34aa42f3b2d6f0107d1eca30354f273723f1ecbc
