### ISSUE TITLE
baking in one texture

### ISSUE THREAD

**Issue by MikhalenkaA** [xjorma/EarthMeshHoudini#3]
Hello, There is any possibility to bake all textures in one, for export it to another application and do not have  a thousandth materials?

**Comment by xjorma** [comment]
No but I will think about that.
I agree could help the setup but also limits the number of drawcalls in a game engine.

**Comment by xjorma** [comment]
Probably solution already exist inside houdini.

**Comment by MikhalenkaA** [comment]
I mainly need it for 3ds max. and one more question, there is any possibility to select exact area that I need to receive? as for now it downloading too much and in viewport I see whole glode :)

**Comment by xjorma** [comment]
Preview version with texture atlas is available.

**Comment by xjorma** [comment]
now even work with apprentice.
