### ISSUE TITLE
No texture with new version

### ISSUE THREAD

**Issue by ProvencherRoyPR** [xjorma/EarthMeshHoudini#4]
Hello! Tried the new version and I only get a white material while old version still works.

The log would mention that it could not find some local files.

**Comment by xjorma** [comment]
Which Houdini license type  are you using? Unfortunately I just tested against the "Apprentice" version and it doesn't work. Apprentice version disallow to export texture bellow 1280 x 720, you can try with 512 x 512. It works **but** unfortunately it adds a watermark,

**Comment by ProvencherRoyPR** [comment]
I am indeed using an apprentice version. Not sure where to input resolution. I'm getting a white model as soon as it's done generating. I am also not used to houdini much maybe you mean a setting inside Houdini. Thank you for responding

**Comment by xjorma** [comment]
Ok the new version should works with apprentice.

**Comment by vinyvince** [comment]
I need to test something, Could someone do me a favoir please? Is it possible to have a sample demo scene with some data baked please?
